pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

trigger:
- master

- script: |
    npm install bcrypt
  displayName: 'npm install bcrypt'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'
    
- task: SnykTask@1
  inputs:
    file: 'package.json'
    authType: 'token'
    token: '4f43842f-a23d-4002-9d78-841b9ce6fc57'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'

